name: ðŸ› Bug Report
description: Help us improve by reporting something that is not working as intended.
labels: [bug, 'status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Before you continue...

        Please help us by asking yourself these questions first:

        - Is this clearly a BeAPI defect?

        - Do I have basic ideas about where it goes wrong? (For example, if
        there are stack traces, are they pointing at the core script?)

        - Could it be because of my own mistakes?


        **The GitHub issue tracker is not a support forum.** If you are not sure
        whether it could be your mistakes, ask in the [Discord
        Guild](https://discord.gg/DPRYsU4yf4). The quickest way to verify
        whether it's a BeAPI defect is through a **reproduction**, starting with
        a fresh installation and making changes until the bug is reproduced.


        Make the bug obvious. Ideally, we should be able to understand it
        without running any code.


        Bugs are fixed faster if you include:

        - A reproduction repository to inspect the code

        - A video displaying the bug in action (if feasible)

  - type: checkboxes
    attributes:
      label: Have you read the Issues Contributing Guidelines?
      options:
        - label: I have read the [Issues Contributing Guidelines](https://github.com/MCBE-Utilities/BeAPI/blob/beta/CONTRIBUTING.md#issues).
          required: true
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        Please check the following items before creating a issue. This way we
        know you've done these steps first.
      options:
        - label: I'm using the latest version of BeAPI.
        - label: I have tried deleting and reinstalling `node_modules`?
        - label: I have successfully made a reproduction repository for the bug?
        - label: I have ensured the stack trace points to BeAPI core script?
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Reproducible demo
      description: |
        Paste the link to an example repository with the code to reproduce the
        bug. The repository should include everything given in the scaffold
        template plus any extra files needed to reproduce the bug. 

        > **What happens if you skip this step?** Someone will read your bug report, and maybe will be able to help you, but it's unlikely that it will get much attention from the team. Eventually, the issue will likely get closed in favor of issues that have reproducible demos.

        Please remember that:

        - Issues without reproducible demos have a very low priority.
        - The person fixing the bug would have to do that anyway. Please be respectful of their time.
        - You might figure out the issues yourself as you work on extracting it.

        Thanks for helping us help you!

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Write down the steps to reproduce the bug. You should start with a fresh installation, or your git repository linked above.
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. Step 3...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Write down the steps to reproduce the bug. You should start with a fresh installation, or your git repository linked above.
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. Step 3...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        How did you expect your project to behave? It's fine if you're not sure your understanding is correct. Write down what you thought would happen.
      placeholder: Write what you thought would happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        Did something go wrong? Is something broken, or not behaving as you expected?
        Describe this section in detail, and attach screenshots if possible. Don't only say "it doesn't work"!
        Please submit exhaustive and complete log messages (we also need the error stack-traces, not just the message).
        > Please read error messages carefully: it often tells you exactly what you are doing wrong.
      placeholder: Write what happened. Add full console log messages and screenshots, if applicable.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Your environment
      description: Include as many relevant details about the environment you experienced the bug in.
      value: |
        - Public source code:
        - BeAPI version used:
        - Environment name and version (e.g. Node.js 16.4, Minecraft 1.18.2):
        - Operating system and version (e.g. Windows 11):

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
        If you do check this box, please send a pull request within 7 days so we can still delegate this to someone else.
      options:
        - label: I'd be willing to fix this bug myself.
